uploads = []

[[generated]]
id = "jWeATstLuKdIIejUIOAV6"
uri = "file://artifacts/crrnt/assets/images/icon.png"
type = "image"
title = "crrnt app icon"

[[outputs]]
id = "AHbgnUy25K-YJ1HevNZpn"
uri = "file://artifacts/crrnt/README.md"
type = "text"
title = "CRRNT iOS Build & Development Guide"
